import { useEffect, useState } from "react";
import { BarChart3, RefreshCw } from "lucide-react";
const API_URL=import.meta.env.VITE_API_URL??"http://localhost:4000";
type Report={period:{from:string;to:string};portfolio:{customers:number;totalCredits:number;activeCredits:number;overdueCredits:number;paidCredits:number;outstandingBalance:number;overdueAmount:number;financedDevices:number};periodMetrics:{placedCredits:number;placedAmount:number;principalPlaced:number;collected:number;creditPayments:number;downPayments:number;paymentCount:number};paymentsByMethod:{method:string;amount:number}[];generatedAt:string};
const money=(v:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(v||0);
export default function ReportsPage(){
 const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10);
 const [from,setFrom]=useState(first),[to,setTo]=useState(now.toISOString().slice(0,10)),[data,setData]=useState<Report|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const token=sessionStorage.getItem("movicredito_token");const r=await fetch(`${API_URL}/api/reports/summary?from=${from}&to=${to}`,{headers:{Authorization:`Bearer ${token}`}});const b=await r.json();if(!r.ok)throw new Error(b.message||"No fue posible generar el reporte.");setData(b);}catch(e){setError(e instanceof Error?e.message:"No fue posible generar el reporte.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const card=(label:string,value:string|number,sub:string)=><div className="rounded-[26px] border border-blue-100 bg-white p-5 shadow-[0_18px_55px_-32px_rgba(37,99,235,0.45)]"><p className="text-xs font-semibold uppercase tracking-[.12em] text-blue-900/45">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight text-[#1d1d1f]">{value}</p><p className="mt-1 text-xs text-slate-500">{sub}</p></div>;
 return <section className="min-h-[calc(100vh-72px)] bg-gradient-to-br from-blue-50 via-white to-indigo-50 px-6 py-8 sm:px-8 lg:px-12 lg:py-11"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col gap-5 border-b border-blue-100 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-black/30">MoviCrédito Admin</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.045em] text-[#1d1d1f]">Reportes</h1><p className="mt-3 text-sm text-slate-600">Cartera, colocación y recuperación calculadas con información real de la operación.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs text-slate-600">Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block rounded-xl border border-black/10 px-3 py-2 text-sm text-black"/></label><label className="text-xs text-slate-600">Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block rounded-xl border border-black/10 px-3 py-2 text-sm text-black"/></label><button onClick={load} disabled={loading} className="flex h-10 items-center gap-2 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 px-4 text-sm font-semibold text-white shadow-lg shadow-blue-600/15 disabled:opacity-40"><RefreshCw size={15}/>{loading?"Calculando...":"Actualizar"}</button></div></div>
  {error&&<div className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {data&&<><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{card("Saldo de cartera",money(data.portfolio.outstandingBalance),`${data.portfolio.activeCredits+data.portfolio.overdueCredits} créditos vigentes`)}{card("Cartera vencida",money(data.portfolio.overdueAmount),`${data.portfolio.overdueCredits} créditos vencidos`)}{card("Cobrado en periodo",money(data.periodMetrics.collected),`${data.periodMetrics.paymentCount} pagos aplicados`)}{card("Colocación",money(data.periodMetrics.placedAmount),`${data.periodMetrics.placedCredits} créditos colocados`)}</div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-[28px] border border-blue-100 p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><BarChart3 size={19}/>Cartera actual</h2><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><p className="text-slate-500">Clientes</p><p className="mt-1 text-xl font-semibold">{data.portfolio.customers}</p></div><div><p className="text-slate-500">Equipos financiados</p><p className="mt-1 text-xl font-semibold">{data.portfolio.financedDevices}</p></div><div><p className="text-slate-500">Créditos pagados</p><p className="mt-1 text-xl font-semibold">{data.portfolio.paidCredits}</p></div><div><p className="text-slate-500">Créditos totales</p><p className="mt-1 text-xl font-semibold">{data.portfolio.totalCredits}</p></div></div></div>
  <div className="rounded-[28px] border border-blue-100 p-6"><h2 className="text-lg font-semibold">Recuperación del periodo</h2><div className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><span className="text-slate-600">Pagos a crédito</span><b>{money(data.periodMetrics.creditPayments)}</b></div><div className="flex justify-between"><span className="text-slate-600">Enganches</span><b>{money(data.periodMetrics.downPayments)}</b></div><div className="flex justify-between border-t border-blue-100 pt-4"><span className="text-slate-600">Principal colocado</span><b>{money(data.periodMetrics.principalPlaced)}</b></div></div></div></div>
  <div className="mt-6 rounded-[28px] border border-blue-100 p-6"><h2 className="text-lg font-semibold">Cobranza por método</h2><div className="mt-4 divide-y divide-black/5">{data.paymentsByMethod.length?data.paymentsByMethod.map(x=><div key={x.method} className="flex justify-between py-3 text-sm"><span className="capitalize text-black/50">{x.method.replaceAll("_"," ")}</span><b>{money(x.amount)}</b></div>):<p className="py-6 text-sm text-blue-900/45">Sin pagos aplicados en el periodo.</p>}</div></div></>}
 </div></section>;
}
