import { useEffect, useMemo, useState } from "react";
import { Eye, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import Pagination from "../../../components/admin/shared/Pagination";
const API_URL=import.meta.env.VITE_API_URL||"";
type Log={id:string;userId?:string;action:string;entityType:string;entityId?:string;metadata?:Record<string,unknown>;ip?:string;createdAt:string;user?:{fullName:string;email:string;role:string}|null};
const actionLabel=(v:string)=>v.replaceAll("_"," ").replaceAll("."," · ");
export default function AuditPage(){
 const token=sessionStorage.getItem("movicredito_token"); const headers={Authorization:`Bearer ${token}`};
 const [logs,setLogs]=useState<Log[]>([]);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const pageSize=30;const [filters,setFilters]=useState<any>({actions:[],entityTypes:[],users:[]});const [selected,setSelected]=useState<Log|null>(null);const [loading,setLoading]=useState(true);
 const [search,setSearch]=useState("");const [action,setAction]=useState("");const [entityType,setEntityType]=useState("");const [userId,setUserId]=useState("");const [dateFrom,setDateFrom]=useState("");const [dateTo,setDateTo]=useState("");
 const query=useMemo(()=>{const p=new URLSearchParams();if(search)p.set("search",search);if(action)p.set("action",action);if(entityType)p.set("entityType",entityType);if(userId)p.set("userId",userId);if(dateFrom)p.set("dateFrom",dateFrom);if(dateTo)p.set("dateTo",dateTo);p.set("pageSize",String(pageSize));p.set("page",String(page));return p.toString()},[search,action,entityType,userId,dateFrom,dateTo,page]);
 const load=async()=>{setLoading(true);try{const r=await fetch(`${API_URL}/api/audit?${query}`,{headers});const b=await r.json();if(!r.ok)throw new Error(b.message);setLogs(b.items||[]);setTotal(b.total||0);}finally{setLoading(false)}};
 useEffect(()=>{fetch(`${API_URL}/api/audit/filters`,{headers}).then(r=>r.json()).then(setFilters).catch(()=>{});},[]);
 useEffect(()=>{setPage(1)},[search,action,entityType,userId,dateFrom,dateTo]);
 useEffect(()=>{const id=setTimeout(()=>void load(),250);return()=>clearTimeout(id)},[query]);
 return <section className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50 px-5 py-8 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Trazabilidad y seguridad</p><h1 className="mt-1 text-4xl font-semibold tracking-[-.045em]">Auditoría</h1><p className="mt-2 text-sm text-slate-600">Consulta quién realizó acciones sensibles, cuándo y sobre qué registro.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium shadow-sm"><RefreshCw size={16}/>Actualizar</button></div>
 <div className="mt-7 rounded-[26px] bg-white p-4 shadow-sm ring-1 ring-blue-100"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><div className="relative xl:col-span-2"><Search size={16} className="absolute left-4 top-4 text-black/30"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Acción, entidad o ID" className="h-12 w-full rounded-2xl bg-blue-50 pl-11 pr-4 text-sm outline-none"/></div><select value={action} onChange={e=>setAction(e.target.value)} className="h-12 rounded-2xl bg-blue-50 px-3 text-sm outline-none"><option value="">Todas las acciones</option>{filters.actions?.map((x:string)=><option key={x} value={x}>{actionLabel(x)}</option>)}</select><select value={userId} onChange={e=>setUserId(e.target.value)} className="h-12 rounded-2xl bg-blue-50 px-3 text-sm outline-none"><option value="">Todos los usuarios</option>{filters.users?.map((u:any)=><option key={u.id} value={u.id}>{u.fullName}</option>)}</select><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="h-12 rounded-2xl bg-blue-50 px-3 text-sm outline-none"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="h-12 rounded-2xl bg-blue-50 px-3 text-sm outline-none"/></div></div>
 <div className="mt-5 overflow-hidden rounded-[28px] bg-white shadow-sm ring-1 ring-blue-100"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-blue-50 text-[11px] uppercase tracking-wide text-blue-900/45"><tr><th className="px-5 py-4">Fecha</th><th className="px-5 py-4">Usuario</th><th className="px-5 py-4">Acción</th><th className="px-5 py-4">Entidad</th><th className="px-5 py-4">IP</th><th className="px-5 py-4">Detalle</th></tr></thead><tbody className="divide-y divide-black/5">{loading?<tr><td colSpan={6} className="px-5 py-12 text-center text-blue-900/45">Consultando bitácora…</td></tr>:logs.length===0?<tr><td colSpan={6} className="px-5 py-12 text-center text-blue-900/45">No hay eventos con estos filtros.</td></tr>:logs.map(log=><tr key={log.id} className="hover:bg-black/[.015]"><td className="px-5 py-4 whitespace-nowrap">{new Date(log.createdAt).toLocaleString("es-MX")}</td><td className="px-5 py-4"><span className="block font-medium">{log.user?.fullName||"Sistema"}</span><span className="text-xs text-blue-900/45">{log.user?.role||"Automático"}</span></td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs">{actionLabel(log.action)}</span></td><td className="px-5 py-4"><span className="block">{log.entityType}</span><span className="block max-w-[180px] truncate font-mono text-[10px] text-black/30">{log.entityId||"—"}</span></td><td className="px-5 py-4 text-xs text-slate-600">{log.ip||"—"}</td><td className="px-5 py-4"><button onClick={()=>setSelected(log)} className="rounded-full bg-blue-50 p-2"><Eye size={15}/></button></td></tr>)}</tbody></table></div><Pagination page={page} total={total} pageSize={pageSize} onPageChange={setPage}/></div>
 {selected&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/30 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-[30px] bg-white p-7 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="text-sm text-slate-500">Evento de auditoría</p><h2 className="mt-1 text-xl font-semibold">{actionLabel(selected.action)}</h2></div><button onClick={()=>setSelected(null)} className="rounded-full bg-blue-50 p-2"><X size={18}/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Card label="Usuario" value={selected.user?.fullName||"Sistema"}/><Card label="Fecha" value={new Date(selected.createdAt).toLocaleString("es-MX")}/><Card label="Entidad" value={selected.entityType}/><Card label="ID" value={selected.entityId||"—"}/><Card label="IP" value={selected.ip||"—"}/></div><div className="mt-3 rounded-2xl bg-blue-50 p-4"><p className="text-xs uppercase tracking-wide text-blue-900/45">Metadata</p><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs text-black/60">{JSON.stringify(selected.metadata||{},null,2)}</pre></div><div className="mt-4 flex items-center gap-2 text-xs text-blue-900/45"><ShieldCheck size={14}/>Registro de solo lectura para conservar trazabilidad.</div></div></div>}</div></section>
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs text-blue-900/45">{label}</p><p className="mt-1 break-all text-sm font-medium">{value}</p></div>}
