import { useEffect, useState } from "react";
import { KeyRound, Mail, ShieldCheck } from "lucide-react";
const API_URL=import.meta.env.VITE_API_URL||"";
export default function SecurityPage(){
 const token=sessionStorage.getItem("movicredito_token"); const [method,setMethod]=useState("email"); const [enabled,setEnabled]=useState(false); const [qr,setQr]=useState(""); const [secret,setSecret]=useState(""); const [code,setCode]=useState(""); const [message,setMessage]=useState("");
 const request=async(url:string,options?:RequestInit)=>{const r=await fetch(`${API_URL}${url}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options?.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||"No fue posible completar la operación.");return b};
 useEffect(()=>{void request("/api/auth/2fa").then(b=>{setMethod(b.method);setEnabled(b.totpEnabled)}).catch(e=>setMessage(e.message))},[]);
 const setup=async()=>{try{setMessage("");const b=await request("/api/auth/2fa/totp/setup",{method:"POST"});setQr(b.qrDataUrl);setSecret(b.secret)}catch(e){setMessage((e as Error).message)}};
 const confirm=async()=>{try{const b=await request("/api/auth/2fa/totp/confirm",{method:"POST",body:JSON.stringify({code})});setMethod(b.method);setEnabled(true);setQr("");setSecret("");setCode("");setMessage("Aplicación de autenticación activada.")}catch(e){setMessage((e as Error).message)}};
 const email=async()=>{try{await request("/api/auth/2fa/email",{method:"POST"});setMethod("email");setQr("");setSecret("");setMessage("Verificación por correo activada.")}catch(e){setMessage((e as Error).message)}};
 return <section className="min-h-screen bg-[#f5f5f7] px-4 py-8 md:px-8"><div className="mx-auto max-w-4xl"><p className="text-sm font-medium text-black/40">Cuenta</p><h1 className="mt-1 text-4xl font-semibold tracking-[-0.045em]">Seguridad</h1><p className="mt-2 text-sm text-black/45">Elige cómo confirmar tus inicios de sesión.</p>
 <div className="mt-7 grid gap-4 md:grid-cols-2"><button onClick={()=>void email()} className={`rounded-[24px] bg-white p-6 text-left ring-1 ${method==="email"?"ring-black":"ring-black/5"}`}><Mail/><h2 className="mt-4 font-semibold">Código por correo</h2><p className="mt-2 text-sm text-black/45">Recibe un código de 6 dígitos en tu correo.</p>{method==="email"&&<p className="mt-4 text-xs font-semibold">Activo</p>}</button>
 <button onClick={()=>void setup()} className={`rounded-[24px] bg-white p-6 text-left ring-1 ${method==="totp"?"ring-black":"ring-black/5"}`}><KeyRound/><h2 className="mt-4 font-semibold">Aplicación de autenticación</h2><p className="mt-2 text-sm text-black/45">Compatible con Google Authenticator, Microsoft Authenticator y otras apps TOTP.</p>{method==="totp"&&enabled&&<p className="mt-4 text-xs font-semibold">Activo</p>}</button></div>
 {qr&&<div className="mt-6 rounded-[28px] bg-white p-6 ring-1 ring-black/5"><div className="flex items-center gap-2"><ShieldCheck size={18}/><h2 className="font-semibold">Enlazar autenticador</h2></div><p className="mt-2 text-sm text-black/45">Escanea el QR y confirma con el código generado por tu aplicación.</p><img src={qr} alt="QR para autenticador" className="mt-5 h-52 w-52 rounded-2xl border border-black/5"/><details className="mt-3 text-xs text-black/45"><summary>Configurar manualmente</summary><code className="mt-2 block break-all rounded-xl bg-[#f5f5f7] p-3">{secret}</code></details><div className="mt-5 flex max-w-md gap-3"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" placeholder="000000" className="h-12 min-w-0 flex-1 rounded-2xl bg-[#f5f5f7] px-4 text-center tracking-[.3em] outline-none"/><button onClick={()=>void confirm()} disabled={code.length!==6} className="rounded-full bg-black px-5 text-sm font-medium text-white disabled:opacity-40">Confirmar</button></div></div>}
 {message&&<div className="mt-5 rounded-2xl bg-white px-4 py-3 text-sm ring-1 ring-black/5">{message}</div>}
 </div></section>
}