const TOKEN_KEY="movicredito_token"; const USER_KEY="movicredito_user";
const API_URL=import.meta.env.VITE_API_URL||"";
export function clearMoviCreditoSession(){sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(USER_KEY);}
export function getMoviCreditoToken(){return sessionStorage.getItem(TOKEN_KEY);}
export function getJwtExpirationMs(token:string):number|null{try{const p=JSON.parse(atob(token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/")));return typeof p?.exp==="number"?p.exp*1000:null}catch{return null}}
export function isJwtExpired(token:string,clockSkewMs=5000){const e=getJwtExpirationMs(token);return !e||e<=Date.now()+clockSkewMs;}
export function expireMoviCreditoSession(){clearMoviCreditoSession();if(window.location.pathname!=="/login")window.location.replace("/login?reason=session-expired");}
let installed=false; let refreshing:Promise<string|null>|null=null;
async function refreshAccessToken(originalFetch:typeof window.fetch){if(refreshing)return refreshing;refreshing=(async()=>{try{const r=await originalFetch(`${API_URL}/api/auth/refresh`,{method:"POST",credentials:"include"});if(!r.ok)return null;const b=await r.json();if(!b.token)return null;sessionStorage.setItem(TOKEN_KEY,b.token);if(b.user)sessionStorage.setItem(USER_KEY,JSON.stringify(b.user));return b.token as string}catch{return null}finally{refreshing=null}})();return refreshing;}
export async function restoreMoviCreditoSession(){const nativeFetch=window.fetch.bind(window);const token=getMoviCreditoToken();if(token&&!isJwtExpired(token))return token;return refreshAccessToken(nativeFetch);}
export function installAuthFetchInterceptor(){if(installed)return;installed=true;const originalFetch=window.fetch.bind(window);window.fetch=async(input,init)=>{let requestInit={...init,credentials:init?.credentials||"include"} as RequestInit;let response=await originalFetch(input,requestInit);const headers=new Headers(requestInit.headers||((input instanceof Request)?input.headers:{}));const auth=headers.get("Authorization");const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url;if(response.status===401&&auth?.startsWith("Bearer ")&&!url.includes("/api/auth/refresh")){const fresh=await refreshAccessToken(originalFetch);if(fresh){headers.set("Authorization",`Bearer ${fresh}`);response=await originalFetch(input,{...requestInit,headers});return response;}expireMoviCreditoSession();}return response;};}
