import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Check, CheckCircle2, ClipboardCheck, FileText, RefreshCw, ShieldCheck, X, XCircle } from "lucide-react";

const API_URL = import.meta.env.VITE_API_URL || "";

type Application = { id:string; folio:string; fullName:string; email:string; phone:string; productId:number; downPayment:number|string; termMonths:number; monthlyIncome:number|string; status:string; curp?:string; rfc?:string; address?:string; postalCode?:string; occupation?:string; employer?:string };
type Product = { id:number; brand:string; model:string; storage:string; price:number|string };
type Device = { id:string; productId:number; imei:string; serial?:string; status:string };
type DocumentRow = { id:string; type:string; originalName:string; reviewStatus:"pending"|"accepted"|"rejected" };
type Reference = { id:string; fullName:string; phone:string; relationship?:string };
type Factor = { points:number; detail:string };
type Risk = { score:number; riskLevel:"low"|"medium"|"high"|"very_high"; recommendation:"approve"|"manual_review"|"reject"; factors:Record<string,Factor> };
type Review = { application:Application; product:Product|null; documents:DocumentRow[]; references:Reference[]; risk:Risk|null };
type Fulfillment = { id:string; deviceId?:string; status:"contract_pending"|"down_payment_pending"|"device_pending"|"ready_for_activation"|"active"|"cancelled"; contractStatus:"pending"|"signed"; downPaymentStatus:"pending"|"paid"; financingSnapshot:Record<string,unknown> };
type Contract = { id:string; version:number; status:"generated"|"accepted"|"void"; documentHash:string };
type DownPayment = { id:string; provider:string; externalReference:string; expectedAmount:number|string; paidAmount?:number|string; status:"pending"|"approved"|"rejected"|"cancelled" };

const riskLabels = { low:"Bajo", medium:"Medio", high:"Alto", very_high:"Muy alto" } as const;
const recommendationLabels = { approve:"Recomienda aprobar", manual_review:"Revisión manual", reject:"Recomienda rechazar" } as const;
const fulfillmentLabels:Record<Fulfillment["status"],string> = { contract_pending:"Contrato pendiente", down_payment_pending:"Enganche pendiente", device_pending:"IMEI pendiente", ready_for_activation:"Listo para activar", active:"Crédito activo", cancelled:"Cancelado" };

export default function ApplicationsPage(){
  const token=sessionStorage.getItem("movicredito_token");
  const authHeaders={Authorization:`Bearer ${token}`};
  const jsonHeaders={...authHeaders,"Content-Type":"application/json"};
  const [applications,setApplications]=useState<Application[]>([]); const [products,setProducts]=useState<Product[]>([]); const [devices,setDevices]=useState<Device[]>([]);
  const [selectedId,setSelectedId]=useState<string|null>(null); const [review,setReview]=useState<Review|null>(null); const [fulfillment,setFulfillment]=useState<Fulfillment|null>(null);
  const [contract,setContract]=useState<Contract|null>(null); const [downPayment,setDownPayment]=useState<DownPayment|null>(null); const [selectedDeviceId,setSelectedDeviceId]=useState("");
  const [decisionReason,setDecisionReason]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);

  const load=async()=>{ const [a,p,d]=await Promise.all([fetch(`${API_URL}/api/credit-applications`,{headers:authHeaders}),fetch(`${API_URL}/api/products`),fetch(`${API_URL}/api/devices`,{headers:authHeaders})]); if(a.ok)setApplications(await a.json()); if(p.ok)setProducts(await p.json()); if(d.ok)setDevices(await d.json()); };
  useEffect(()=>{void load();},[]);
  const productMap=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);

  const loadFulfillment=async(applicationId:string)=>{
    const [f,c,p]=await Promise.all([
      fetch(`${API_URL}/api/credit-applications/${applicationId}/fulfillment`,{headers:authHeaders}),
      fetch(`${API_URL}/api/credit-applications/${applicationId}/contract`,{headers:authHeaders}),
      fetch(`${API_URL}/api/down-payments/applications/${applicationId}`,{headers:authHeaders}),
    ]);
    if(f.ok){const body=await f.json();setFulfillment(body);setSelectedDeviceId(body.deviceId||"");}else setFulfillment(null);
    setContract(c.ok?await c.json():null); setDownPayment(p.ok?await p.json():null);
  };
  const openReview=async(applicationId:string)=>{setSelectedId(applicationId);setReview(null);setFulfillment(null);setContract(null);setDownPayment(null);setDecisionReason("");setMessage(null);const r=await fetch(`${API_URL}/api/credit-applications/${applicationId}/review`,{headers:authHeaders});const b=await r.json().catch(()=>({}));if(!r.ok){setMessage(b.message||"No fue posible cargar el expediente.");return;}setReview(b);if(b.application?.status==="approved")await loadFulfillment(applicationId);};
  const evaluateRisk=async()=>{if(!selectedId)return;setBusy("risk");const r=await fetch(`${API_URL}/api/risk/applications/${selectedId}/evaluate`,{method:"POST",headers:authHeaders});const b=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMessage(b.message||"No fue posible evaluar el riesgo.");return;}await openReview(selectedId);};
  const reviewDocument=async(document:DocumentRow,status:"accepted"|"rejected")=>{if(!selectedId)return;const reason=status==="rejected"?(window.prompt("Motivo de rechazo:")||"").trim():"";if(status==="rejected"&&reason.length<4)return;setBusy(document.id);const r=await fetch(`${API_URL}/api/credit-applications/${selectedId}/documents/${document.id}/review`,{method:"PATCH",headers:jsonHeaders,body:JSON.stringify({reviewStatus:status,reason})});const b=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMessage(b.message||"No fue posible revisar el documento.");return;}await openReview(selectedId);};
  const decide=async(decision:"approve"|"reject")=>{if(!review)return;if(decisionReason.trim().length<8){setMessage("Captura un motivo de al menos 8 caracteres.");return;}setBusy(decision);const r=await fetch(`${API_URL}/api/credit-applications/${review.application.id}/${decision}`,{method:"POST",headers:jsonHeaders,body:JSON.stringify({reason:decisionReason.trim()})});const b=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMessage(b.message||"No fue posible procesar la decisión.");return;}setMessage(decision==="approve"?"Solicitud aprobada. Genera el contrato para continuar.":"Solicitud rechazada.");await load();await openReview(review.application.id);};
  const postApplication=async(path:string,body?:Record<string,unknown>)=>{if(!review)return;setBusy(path);const r=await fetch(`${API_URL}/api/credit-applications/${review.application.id}/${path}`,{method:"POST",headers:jsonHeaders,body:body?JSON.stringify(body):undefined});const b=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMessage(b.message||"No fue posible completar la operación.");return;}await load();await openReview(review.application.id);};
  const generateContract=async()=>{if(!review)return;setBusy("contract");const r=await fetch(`${API_URL}/api/credit-applications/${review.application.id}/contract/generate`,{method:"POST",headers:authHeaders});const b=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMessage(b.message||"No fue posible generar el contrato.");return;}setMessage(`Contrato v${b.version} generado. El cliente debe aceptarlo desde el portal de contrato.`);await loadFulfillment(review.application.id);};
  const createDownPayment=async()=>{if(!review)return;setBusy("down-payment");const r=await fetch(`${API_URL}/api/down-payments/applications/${review.application.id}/request`,{method:"POST",headers:jsonHeaders,body:JSON.stringify({provider:"external"})});const b=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMessage(b.message||"No fue posible crear la referencia de enganche.");return;}setDownPayment(b);setMessage(`Referencia de enganche creada: ${b.externalReference}. Se confirmará únicamente por webhook.`);};
  const compatibleDevices=review?devices.filter(d=>d.productId===review.application.productId&&(d.status==="available"||d.id===fulfillment?.deviceId)):[];
  const prerequisitesPaid=fulfillment?.contractStatus==="signed"&&fulfillment?.downPaymentStatus==="paid";

  return <section className="min-h-screen bg-[#f5f5f7] px-4 py-8 md:px-8"><div className="mx-auto max-w-7xl">
    <div className="flex items-end justify-between gap-4"><div><p className="text-sm text-black/40">Originación</p><h1 className="mt-1 text-4xl font-semibold tracking-[-0.045em]">Solicitudes de crédito</h1><p className="mt-2 text-sm text-black/45">KYC, riesgo, contrato, enganche, IMEI y activación.</p></div><button onClick={()=>void load()} className="rounded-full bg-white p-3 shadow-sm ring-1 ring-black/5"><RefreshCw size={17}/></button></div>
    {message&&<div className="mt-6 rounded-2xl bg-white px-5 py-4 text-sm text-black/60 shadow-sm ring-1 ring-black/5">{message}</div>}
    <div className="mt-7 overflow-hidden rounded-[28px] bg-white shadow-sm ring-1 ring-black/5"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#fafafa] text-xs uppercase tracking-wide text-black/35"><tr><th className="px-6 py-4">Folio</th><th className="px-6 py-4">Cliente</th><th className="px-6 py-4">Equipo</th><th className="px-6 py-4">Estado</th><th className="px-6 py-4">Acción</th></tr></thead><tbody className="divide-y divide-black/5">{applications.map(app=>{const product=productMap.get(app.productId);return <tr key={app.id}><td className="px-6 py-4 font-mono text-xs">{app.folio}</td><td className="px-6 py-4"><p className="font-medium">{app.fullName}</p><p className="text-xs text-black/35">{app.email} · {app.phone}</p></td><td className="px-6 py-4">{product?`${product.brand} ${product.model}`:`Producto ${app.productId}`}</td><td className="px-6 py-4"><span className="rounded-full bg-[#f5f5f7] px-3 py-1.5 text-xs capitalize">{app.status}</span></td><td className="px-6 py-4"><button onClick={()=>void openReview(app.id)} className="inline-flex items-center gap-2 rounded-full border border-black/10 px-4 py-2 text-xs font-medium"><ClipboardCheck size={14}/> Revisar</button></td></tr>})}</tbody></table></div></div>
  </div>

  {selectedId&&<div className="fixed inset-0 z-50 flex justify-end bg-black/25 backdrop-blur-sm"><div className="h-full w-full max-w-2xl overflow-y-auto bg-[#f5f5f7] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-black/5 bg-white/90 px-6 py-5"><div><p className="text-xs uppercase tracking-[.14em] text-black/35">Expediente</p><h2 className="mt-1 text-xl font-semibold">{review?.application.folio||"Cargando…"}</h2></div><button onClick={()=>{setSelectedId(null);setReview(null);}} className="rounded-full bg-[#f5f5f7] p-2"><X size={18}/></button></div>
    {!review?<div className="p-8 text-sm text-black/40">Cargando expediente…</div>:<div className="space-y-5 p-6">
      <Card><div className="flex items-start justify-between"><div><p className="text-sm text-black/40">Solicitante</p><h3 className="mt-1 text-2xl font-semibold">{review.application.fullName}</h3><p className="mt-1 text-sm text-black/45">{review.application.curp||"CURP pendiente"} · {review.application.rfc||"RFC pendiente"}</p></div><ShieldCheck className="text-black/25"/></div></Card>
      <Card><div className="flex items-center justify-between"><div><p className="text-sm text-black/40">Riesgo interno</p><h3 className="mt-1 text-lg font-semibold">{review.risk?`${review.risk.score} · ${riskLabels[review.risk.riskLevel]}`:"Sin evaluar"}</h3></div>{review.application.status==="pending"&&<button onClick={()=>void evaluateRisk()} disabled={busy==="risk"} className="rounded-full bg-black px-4 py-2 text-xs text-white disabled:opacity-40">Evaluar</button>}</div>{review.risk&&<><p className="mt-3 text-sm font-medium">{recommendationLabels[review.risk.recommendation]}</p><div className="mt-4 space-y-2">{Object.entries(review.risk.factors).map(([k,f])=><div key={k} className="flex justify-between rounded-2xl bg-[#f5f5f7] px-4 py-3 text-sm"><span>{f.detail}</span><strong>{f.points>=0?"+":""}{f.points}</strong></div>)}</div></>}</Card>
      <Card><p className="text-sm text-black/40">KYC</p><div className="mt-4 space-y-2">{review.documents.map(doc=><div key={doc.id} className="flex items-center gap-3 rounded-2xl bg-[#f5f5f7] p-4"><div className="flex-1"><p className="text-sm font-medium capitalize">{doc.type.replaceAll("_"," ")}</p><p className="text-xs text-black/35">{doc.originalName} · {doc.reviewStatus}</p></div>{review.application.status==="pending"&&<><button onClick={()=>void reviewDocument(doc,"accepted")} className="rounded-full bg-white p-2 text-emerald-700"><Check size={14}/></button><button onClick={()=>void reviewDocument(doc,"rejected")} className="rounded-full bg-white p-2 text-red-600"><X size={14}/></button></>}</div>)}</div></Card>
      {review.application.status==="pending"&&<Card><p className="text-sm text-black/40">Decisión</p><textarea value={decisionReason} onChange={e=>setDecisionReason(e.target.value)} rows={3} className="mt-3 w-full rounded-2xl border border-black/10 bg-[#f5f5f7] p-3" placeholder="Motivo obligatorio…"/><div className="mt-3 flex gap-2"><button disabled={!review.risk||busy==="approve"} onClick={()=>void decide("approve")} className="flex-1 rounded-full bg-black px-4 py-3 text-sm text-white disabled:opacity-40">Aprobar</button><button onClick={()=>void decide("reject")} className="flex-1 rounded-full border border-red-200 px-4 py-3 text-sm text-red-600">Rechazar</button></div></Card>}
      {review.application.status==="approved"&&fulfillment&&<Card><div className="flex items-center justify-between"><div><p className="text-sm text-black/40">Preparación</p><h3 className="mt-1 text-lg font-semibold">{fulfillmentLabels[fulfillment.status]}</h3></div>{fulfillment.status==="active"&&<CheckCircle2 className="text-emerald-600"/>}</div><div className="mt-5 space-y-3">
        <Step done={fulfillment.contractStatus==="signed"} title={contract?`Contrato v${contract.version} · ${contract.status}`:"Contrato no generado"} action={fulfillment.contractStatus!=="signed"?<button onClick={()=>void generateContract()} disabled={busy==="contract"||contract?.status==="generated"} className="rounded-full bg-black px-3 py-2 text-xs text-white disabled:opacity-40"><FileText size={13} className="inline mr-1"/>{contract?"Esperando cliente":"Generar"}</button>:null}/>
        <Step done={fulfillment.downPaymentStatus==="paid"} title={downPayment?`Enganche · ${downPayment.status} · ${downPayment.externalReference}`:"Enganche sin referencia"} action={fulfillment.downPaymentStatus!=="paid"?<button onClick={()=>void createDownPayment()} disabled={busy==="down-payment"||downPayment?.status==="pending"} className="rounded-full bg-black px-3 py-2 text-xs text-white disabled:opacity-40">{downPayment?.status==="pending"?"Esperando webhook":"Crear referencia"}</button>:null}/>
        <div className="rounded-2xl bg-[#f5f5f7] p-4"><p className="text-sm font-medium">Reservar IMEI</p><div className="mt-2 flex gap-2"><select value={selectedDeviceId} onChange={e=>setSelectedDeviceId(e.target.value)} disabled={!prerequisitesPaid} className="min-w-0 flex-1 rounded-xl border border-black/10 bg-white px-3 py-2 text-xs disabled:opacity-40"><option value="">Selecciona dispositivo</option>{compatibleDevices.map(d=><option key={d.id} value={d.id}>{d.imei}{d.serial?` · ${d.serial}`:""}</option>)}</select><button disabled={!prerequisitesPaid||!selectedDeviceId||selectedDeviceId===fulfillment.deviceId} onClick={()=>void postApplication("fulfillment/device",{deviceId:selectedDeviceId})} className="rounded-full bg-black px-3 py-2 text-xs text-white disabled:opacity-30">Reservar</button></div></div>
        <Step done={fulfillment.status==="active"} title="Activar crédito" action={fulfillment.status==="ready_for_activation"?<button onClick={()=>void postApplication("activate")} className="rounded-full bg-emerald-600 px-4 py-2 text-xs font-medium text-white">Activar</button>:null}/>
      </div></Card>}
    </div>}
  </div></div>}
  </section>;
}

function Card({children}:{children:ReactNode}){return <div className="rounded-[28px] bg-white p-6 shadow-sm ring-1 ring-black/5">{children}</div>}
function Step({done,title,action}:{done:boolean;title:string;action:ReactNode}){return <div className="flex items-center gap-3 rounded-2xl bg-[#f5f5f7] p-4"><span className={`grid h-7 w-7 place-items-center rounded-full ${done?"bg-black text-white":"bg-white text-black/30"}`}>{done?<Check size={14}/>:"•"}</span><p className="flex-1 text-sm font-medium">{title}</p>{action}</div>}
