import { useEffect, useState } from "react";
import { Eye, Search, Smartphone, X } from "lucide-react";
import Pagination from "../../../components/admin/shared/Pagination";

const API_URL = import.meta.env.VITE_API_URL || "";
const statusText:Record<string,string>={assigned:"Asignado",locked:"Bloqueado",reserved:"Reservado",available:"Disponible",retired:"Retirado",active:"Administrado",restricted:"Restringido",released:"Liberado",pending:"Pendiente",unenrolled:"Sin enrolar"};
const label=(value?:string)=>value?statusText[value]||value:"—";
const money=(value:number|string|undefined)=>value===undefined?"—":new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(value));
type Device={id:string;productId:number;imei:string;serial?:string;color?:string;status:string;creditId?:string;customerId?:string;knoxDeviceId?:string;managementStatus:string;customer?:{id:string;fullName:string;email:string}|null;product?:{id:number;brand:string;model:string;storage:string}|null;credit?:{id:string;balance:number|string;status:string}|null};

export default function DevicesPage(){
  const token=sessionStorage.getItem("movicredito_token");
  const headers={Authorization:`Bearer ${token}`};
  const [devices,setDevices]=useState<Device[]>([]);
  const [query,setQuery]=useState("");
  const [error,setError]=useState<string|null>(null);
  const [selected,setSelected]=useState<Device|null>(null);
  const [page,setPage]=useState(1); const pageSize=10; const [total,setTotal]=useState(0);

  const load=async()=>{const p=new URLSearchParams({page:String(page),pageSize:String(pageSize),financedOnly:"true"});if(query.trim())p.set("search",query.trim());const r=await fetch(`${API_URL}/api/devices?${p}`,{headers});if(r.ok){const b=await r.json();setDevices(b.items||[]);setTotal(b.pagination?.total||0);}};
  useEffect(()=>{void load();},[page]);
  const search=async()=>{setError(null);setPage(1);await load();};

  return <section className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50 px-4 py-8 md:px-8"><div className="mx-auto max-w-7xl">
    <div><p className="text-sm text-slate-500">Protección y trazabilidad</p><h1 className="mt-1 text-4xl font-semibold tracking-[-0.045em]">Dispositivos</h1><p className="mt-2 text-sm text-slate-600">Aquí aparecen únicamente equipos vendidos o asignados a un crédito, con su IMEI y estado de administración.</p></div>
    <div className="mt-7 flex max-w-xl gap-2 rounded-full bg-white p-1.5 shadow-sm ring-1 ring-blue-100"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="IMEI, serie o Knox Device ID" className="min-w-0 flex-1 bg-transparent px-4 text-sm outline-none"/><button onClick={()=>void search()} className="grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-md shadow-blue-600/20"><Search size={16}/></button></div>
    {error&&<p className="mt-4 text-sm text-red-600">{error}</p>}
    <div className="mt-7 overflow-hidden rounded-[28px] bg-white shadow-sm ring-1 ring-blue-100"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-blue-50 text-xs uppercase tracking-wide text-blue-900/45"><tr><th className="px-6 py-4">Equipo</th><th className="px-6 py-4">Cliente</th><th className="px-6 py-4">IMEI / Serie</th><th className="px-6 py-4">Equipo</th><th className="px-6 py-4">Administración</th><th className="px-6 py-4">Crédito</th><th className="px-6 py-4">Acción</th></tr></thead><tbody className="divide-y divide-black/5">{devices.map(d=><tr key={d.id}><td className="px-6 py-4"><span className="block font-medium">{d.product?`${d.product.brand} ${d.product.model}`:"Equipo"}</span><span className="text-xs text-slate-500">{d.product?.storage||"—"}{d.color?` · ${d.color}`:""}</span></td><td className="px-6 py-4"><span className="block font-medium">{d.customer?.fullName||"—"}</span><span className="text-xs text-blue-900/45">{d.customer?.email||""}</span></td><td className="px-6 py-4"><span className="inline-flex items-center gap-2 font-mono text-xs"><Smartphone size={14}/>{d.imei}</span><span className="mt-1 block text-xs text-blue-900/45">Serie: {d.serial||"—"}</span></td><td className="px-6 py-4"><Badge>{label(d.status)}</Badge></td><td className="px-6 py-4"><Badge>{label(d.managementStatus)}</Badge></td><td className="px-6 py-4"><span className="block font-medium">{money(d.credit?.balance)}</span><span className="text-xs text-blue-900/45">Saldo · {label(d.credit?.status)}</span></td><td className="px-6 py-4"><button onClick={()=>setSelected(d)} className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-2 text-xs"><Eye size={14}/> Ver</button></td></tr>)}{!devices.length&&<tr><td colSpan={7} className="px-6 py-12 text-center text-blue-900/45">No hay dispositivos financiados para mostrar.</td></tr>}</tbody></table></div><Pagination page={page} total={total} pageSize={pageSize} onPageChange={setPage}/></div>
  </div>{selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/30 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[30px] bg-white p-6 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-sm text-slate-500">Dispositivo financiado</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.03em]">{selected.product?`${selected.product.brand} ${selected.product.model}`:"Equipo financiado"}</h2><p className="mt-1 text-sm text-slate-600">{selected.product?.storage||""}{selected.color?` · ${selected.color}`:""} · IMEI {selected.imei}</p></div><button onClick={()=>setSelected(null)} className="shrink-0 rounded-full bg-blue-50 p-3"><X size={17}/></button></div>
<div className="mt-6 rounded-[22px] bg-blue-50 p-5"><p className="text-xs uppercase tracking-wide text-blue-900/45">Asignado a</p><p className="mt-1 text-lg font-semibold">{selected.customer?.fullName||"Cliente no disponible"}</p><p className="text-sm text-slate-500">{selected.customer?.email||""}</p><div className="mt-4 flex flex-wrap gap-2"><Badge>{label(selected.status)}</Badge><Badge>{label(selected.managementStatus)}</Badge></div></div>
<div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="IMEI" value={selected.imei}/><Field label="Número de serie" value={selected.serial}/><Field label="Saldo pendiente" value={money(selected.credit?.balance)}/><Field label="Estado del crédito" value={label(selected.credit?.status)}/></div>
<div className="mt-6 border-t border-blue-100 pt-5"><h3 className="text-sm font-semibold">Administración del dispositivo</h3><p className="mt-1 text-xs text-slate-500">{selected.knoxDeviceId?"El equipo cuenta con un identificador de administración Knox.":"Todavía no hay un Knox Device ID asociado. En modo simulación, los bloqueos y desbloqueos solo actualizan el flujo interno."}</p>{selected.knoxDeviceId&&<div className="mt-3"><Field label="Knox Device ID" value={selected.knoxDeviceId}/></div>}</div>
<details className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3"><summary className="cursor-pointer text-xs font-medium text-black/50">Información técnica</summary><div className="mt-3"><p className="text-xs text-blue-900/45">ID interno del crédito</p><p className="mt-1 break-all font-mono text-xs text-black/55">{selected.creditId||"—"}</p></div></details>
<p className="mt-5 text-xs text-blue-900/45">Este dispositivo está ligado al crédito y al IMEI; los datos principales son de solo lectura para conservar la trazabilidad.</p></div></div>}</section>
}
function Badge({children}:{children:string}){return <span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-medium text-black/60">{children}</span>}

function Field({label,value}:{label:string;value?:string}){return <div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-all text-sm font-medium">{value||"—"}</p></div>}
